version: '3.8'

services:
  node:
    image: node:16-alpine
    command: /bin/sh -c "npm run start:debug"
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - ../:/app
    working_dir: /app
    links:
      - postgres

  postgres:
    image: postgres:12-alpine
    restart: on-failure
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
volumes:
  postgres:
