version: '3.8'

services:
  node:
    image: ${APP_NAME}/node:16-alpine
    build: ./images/node
    command: /bin/sh -c "cd /var/www && npm run start:debug"
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - ../:/var/www
    depends_on:
      - postgres

  postgres:
    image: postgres:12-alpine
    restart: on-failure
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./images/postgres/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
volumes:
  postgres:
