version: '3.8'

services:
  node:
    image: ${COMPOSE_PROJECT_NAME}/node:16-alpine
    build: ./images/node
    command: /bin/sh -c "cd /var/www && pm2-runtime start /var/pm2-ecosystem.config.js"
    ports:
      - ${HTTP_PORT}:80
      - ${SOCKET_PORT}:1234
    volumes:
      - ../:/var/www
    depends_on:
      - postgres

  postgres:
    image: postgres:12-alpine
    restart: on-failure
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./images/postgres/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis:/data
volumes:
  postgres:
  redis:
